export const ALLOWED_CATEGORIES = [
    'General',
    'Personal Advice',
    'Productivity',
    'Planning and Organization',
    'Education and Learning',
    'Programming and Software Development',
    'Data Science and Machine Learning',
    'Artificial Intelligence',
    'Mathematics',
    'Science',
    'Technology',
    'Business and Entrepreneurship',
    'Finance and Investing',
    'Economics',
    'Career and Jobs',
    'Resume and Interview Preparation',
    'Health and Wellness',
    'Fitness and Exercise',
    'Nutrition and Cooking',
    'Travel and Places',
    'Shopping and Product Research',
    'Home and Lifestyle',
    'Legal and Government',
    'Politics and Current Affairs',
    'News and World Events',
    'History and Culture',
    'Philosophy and Religion',
    'Psychology and Relationships',
    'Writing and Communication',
    'Languages and Translation',
    'Books and Literature',
    'Movies and TV',
    'Anime and Manga',
    'Music and Entertainment',
    'Games and Sports',
];